import React, { useState } from 'react';
import { 
  ShieldCheck, Database, Activity, Layers, ArrowRight, Lock, 
  BellRing, Search, BarChart3, TerminalSquare, Network, 
  Cpu, HardDrive, Link, FileCheck2, Users, FileJson
} from 'lucide-react';

export const LandingPage = () => {
  const [activeStep, setActiveStep] = useState(0);

  const navigateToLogin = () => {
    window.location.hash = "/login";
  };


  return (
    <div className="min-h-screen bg-[#fcfbfb] font-sans selection:bg-[#BE3F2F] selection:text-white">
      
      {/* --- NAVBAR --- */}
      <nav className="fixed top-0 w-full bg-white/80 backdrop-blur-md border-b border-[#e8e6e3] z-50">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            {/* Logo Hexagon Icon */}
            <div className="w-8 h-8 bg-[#BE3F2F] rounded flex items-center justify-center transform rotate-90">
                <div className="w-4 h-4 border-2 border-white rounded-sm transform -rotate-90"></div>
            </div>
            <div>
              <h1 className="text-[15px] font-extrabold text-[#1f1e1d] leading-none tracking-wide">ANCHOR</h1>
              <span className="text-[10px] font-bold text-[#8c8b88] uppercase tracking-widest">Enterprise</span>
            </div>
          </div>
          
          <div className="flex items-center gap-8">
            <a href="#" className="text-sm font-medium text-[#5d5c58] hover:text-[#1f1e1d] transition-colors">Documentation</a>
            <a href="#" className="text-sm font-medium text-[#5d5c58] hover:text-[#1f1e1d] transition-colors">API Reference</a>
            <button 
              onClick={navigateToLogin}
              className="bg-[#BE3F2F] hover:bg-[#a63529] text-white px-5 py-2 rounded-lg text-sm font-medium transition-all shadow-sm flex items-center gap-2"
            >
              Sign In <ArrowRight size={16} />
            </button>
          </div>
        </div>
      </nav>

      {/* --- HERO SECTION --- */}
      <section className="pt-40 pb-20 px-6 text-center max-w-4xl mx-auto animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="inline-block mb-4 px-3 py-1 bg-[#f8f7f6] border border-[#e8e6e3] rounded-full text-xs font-bold text-[#8c8b88] uppercase tracking-widest shadow-sm">
          Solana Mainnet Supported
        </div>
        <h2 className="text-5xl md:text-6xl font-extrabold text-[#1f1e1d] tracking-tight mb-6">
          Cryptographic truth for <br/> <span className="text-[#BE3F2F]">enterprise data.</span>
        </h2>
        <p className="text-lg text-[#5d5c58] mb-10 max-w-2xl mx-auto leading-relaxed">
          Ingest massive datasets, route events through Kafka, and permanently anchor Merkle roots to the Solana blockchain with our independently auditable microservice architecture.
        </p>
        <div className="flex justify-center gap-4">
          <button 
            onClick={navigateToLogin}
            className="bg-[#1f1e1d] hover:bg-black text-white px-8 py-3.5 rounded-xl text-sm font-bold transition-all shadow-md"
          >
            Access Console
          </button>
          <button className="bg-white hover:bg-[#f8f7f6] text-[#1f1e1d] border border-[#e8e6e3] px-8 py-3.5 rounded-xl text-sm font-bold transition-all shadow-sm flex items-center gap-2">
            <TerminalSquare size={18} /> View API Docs
          </button>
        </div>
      </section>


      {/* --- FEATURES GRID --- */}
      <section className="py-24 max-w-6xl mx-auto px-6">
        <div className="text-center mb-16">
          <h3 className="text-2xl font-extrabold text-[#1f1e1d] mb-3">Enterprise Console Features</h3>
          <p className="text-[#5d5c58]">Everything you need to monitor and manage your data integrity.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <FeatureCard 
            icon={Search} 
            title="Global Search" 
            desc="Instantly query millions of anchored records by Request ID, Merkle Root, or custom metadata using our optimized indexer." 
          />
          <FeatureCard 
            icon={ShieldCheck} 
            title="Independent Validation" 
            desc="Review cryptographic proofs generated by the Auditor service, guaranteeing your data matches the Solana mainnet." 
          />
          <FeatureCard 
            icon={BellRing} 
            title="Custom Alert Rules" 
            desc="Configure complex P99 latency rules and error rate thresholds with automatic routing to Slack, Email, or Webhooks." 
          />
          <FeatureCard 
            icon={BarChart3} 
            title="Real-time Analytics" 
            desc="Monitor system health, anchor volume, and Kafka queue depths through beautiful, responsive dashboards." 
          />
          <FeatureCard 
            icon={Lock} 
            title="Keycloak IAM" 
            desc="Enterprise-grade Role Based Access Control (RBAC) securely manages who can view, create, or validate anchors." 
          />
          <FeatureCard 
            icon={TerminalSquare} 
            title="AI Assistant" 
            desc="Built-in Gemini AI helps operators debug anchor failures, explain complex Merkle proofs, and write SQL queries." 
          />
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer className="bg-white border-t border-[#e8e6e3] py-10 mt-10">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 bg-[#8c8b88] rounded flex items-center justify-center transform rotate-90 opacity-50">
                <div className="w-2.5 h-2.5 border border-white rounded-[1px] transform -rotate-90"></div>
            </div>
            <span className="text-sm font-bold text-[#8c8b88]">ANCHOR ENTERPRISE © 2026</span>
          </div>
          <div className="flex gap-6 text-sm font-medium text-[#8c8b88]">
            <a href="#" className="hover:text-[#1f1e1d] transition-colors">Privacy</a>
            <a href="#" className="hover:text-[#1f1e1d] transition-colors">Terms</a>
            <a href="#" className="hover:text-[#1f1e1d] transition-colors">Status</a>
          </div>
        </div>
      </footer>

    </div>
  );
};

// --- Helper Component for the Grid ---
const FeatureCard = ({ icon: Icon, title, desc }: { icon: any, title: string, desc: string }) => (
  <div className="bg-white p-6 rounded-2xl border border-[#e8e6e3] hover:border-[#BE3F2F]/40 hover:shadow-lg transition-all duration-300 group">
    <div className="w-10 h-10 bg-[#f8f7f6] border border-[#e8e6e3] rounded-xl flex items-center justify-center mb-5 group-hover:bg-[#BE3F2F] group-hover:border-[#BE3F2F] transition-colors">
      <Icon size={18} className="text-[#5d5c58] group-hover:text-white transition-colors" />
    </div>
    <h4 className="text-[15px] font-bold text-[#1f1e1d] mb-2">{title}</h4>
    <p className="text-[13px] text-[#5d5c58] leading-relaxed">{desc}</p>
  </div>
);