image:
  repository: ghcr.io/anandstomar/major-project/analytics-consumer
  tag: "2fa88674d51fc08868348cec4b03e14d6dd29e2d"
  pullPolicy: Always
spark:
  version: "3.5.1"
  driver:
    cores: 1
    memory: "512m"
  executor:
    instances: 1
    cores: 1
    memory: "512m"
