image:
  repository: ghcr.io/anandstomar/major-project/analytics-consumer
  tag: "4abf86b48b25345e3cb1f35891abd93b886d1910"
  pullPolicy: Always
spark:
  version: "3.5.1"
  driver:
    cores: 1
    memory: "512m"
  executor:
    instances: 1
    cores: 1
    memory: "512m"
