image:
  repository: ghcr.io/anandstomar/major-project/analytics-consumer
  tag: "14f585a15e3df26d7d157177058f6ef7e1355923"
  pullPolicy: Always
spark:
  version: "3.5.1"
  driver:
    cores: 1
    memory: "512m"
  executor:
    instances: 1
    cores: 1
    memory: "512m"
