image:
  repository: ghcr.io/anandstomar/major-project/auth
  tag: 2fa88674d51fc08868348cec4b03e14d6dd29e2d
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8090
imagePullSecrets:
  - name: ghcrpat
env:
  - name: KEYCLOAK_ISSUER
    value: "http://80.225.242.139/auth-server/realms/provenance"
  - name: KEYCLOAK_JWKS_URI
    value: "http://80.225.242.139/auth-server/realms/provenance/protocol/openid-connect/certs"
  - name: KEYCLOAK_URL
    value: "http://80.225.242.139/auth-server"
