image:
  repository: ghcr.io/anandstomar/major-project/indexer-solana
  tag: 242d9d3b0c5f7f93f5c5ce3ad91307db1badf071
replicaCount: 1
service:
  type: ClusterIP
  port: 3000
env:
  SOLANA_HTTP_RPC: "http://solana-rpc:8899"
  SOLANA_PROGRAM_ID: "Fb7znUeRhH1pHHRd5cNtwTxFqL9AheKvDmU1MR4AZ5tq"
  KAFKA_BROKERS: "kafka-external:9092"
  KAFKA_TOPIC: "anchors.completed"
