// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/anchor_submit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnchorSubmitService_SubmitAnchor_FullMethodName = "/anchorsvc.AnchorSubmitService/SubmitAnchor"
)

// AnchorSubmitServiceClient is the client API for AnchorSubmitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnchorSubmitServiceClient interface {
	SubmitAnchor(ctx context.Context, in *AnchorSubmitRequest, opts ...grpc.CallOption) (*AnchorSubmitResponse, error)
}

type anchorSubmitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnchorSubmitServiceClient(cc grpc.ClientConnInterface) AnchorSubmitServiceClient {
	return &anchorSubmitServiceClient{cc}
}

func (c *anchorSubmitServiceClient) SubmitAnchor(ctx context.Context, in *AnchorSubmitRequest, opts ...grpc.CallOption) (*AnchorSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnchorSubmitResponse)
	err := c.cc.Invoke(ctx, AnchorSubmitService_SubmitAnchor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnchorSubmitServiceServer is the server API for AnchorSubmitService service.
// All implementations must embed UnimplementedAnchorSubmitServiceServer
// for forward compatibility.
type AnchorSubmitServiceServer interface {
	SubmitAnchor(context.Context, *AnchorSubmitRequest) (*AnchorSubmitResponse, error)
	mustEmbedUnimplementedAnchorSubmitServiceServer()
}

// UnimplementedAnchorSubmitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnchorSubmitServiceServer struct{}

func (UnimplementedAnchorSubmitServiceServer) SubmitAnchor(context.Context, *AnchorSubmitRequest) (*AnchorSubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAnchor not implemented")
}
func (UnimplementedAnchorSubmitServiceServer) mustEmbedUnimplementedAnchorSubmitServiceServer() {}
func (UnimplementedAnchorSubmitServiceServer) testEmbeddedByValue()                             {}

// UnsafeAnchorSubmitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnchorSubmitServiceServer will
// result in compilation errors.
type UnsafeAnchorSubmitServiceServer interface {
	mustEmbedUnimplementedAnchorSubmitServiceServer()
}

func RegisterAnchorSubmitServiceServer(s grpc.ServiceRegistrar, srv AnchorSubmitServiceServer) {
	// If the following call panics, it indicates UnimplementedAnchorSubmitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnchorSubmitService_ServiceDesc, srv)
}

func _AnchorSubmitService_SubmitAnchor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnchorSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnchorSubmitServiceServer).SubmitAnchor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnchorSubmitService_SubmitAnchor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnchorSubmitServiceServer).SubmitAnchor(ctx, req.(*AnchorSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnchorSubmitService_ServiceDesc is the grpc.ServiceDesc for AnchorSubmitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnchorSubmitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anchorsvc.AnchorSubmitService",
	HandlerType: (*AnchorSubmitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAnchor",
			Handler:    _AnchorSubmitService_SubmitAnchor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/anchor_submit.proto",
}
