FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json* tsconfig.json ./
RUN npm ci

COPY src ./src
RUN npm run build
RUN cp src/anchor_program.json dist/anchor_program.json

FROM node:20-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json* ./
RUN npm ci --production

COPY --from=build /app/dist ./dist

CMD ["node", "dist/solana-listener.js"]