image:
  repository: ghcr.io/anandstomar/major-project/anchoring-scheduler
  tag: 639af98a7bfa57fad9611509d5c8c9e17a7179ff
  pullPolicy: Always
service:
  type: ClusterIP
  port: 4100
imagePullSecrets:
  - name: ghcrpat
env:
  - name: HTTP_PORT
    value: "4100"
  - name: GROUP_ID
    value: "anchoring-scheduler-group"
  - name: KAFKA_BROKERS
    value: "kafka-external:9092"
  - name: KAFKA_CLIENT_ID
    value: "anchoring-scheduler"
  - name: ANCHORS_PREVIEW_TOPIC
    value: "anchors.preview"
  - name: ANCHORS_REQUEST_TOPIC
    value: "anchors.request"
  - name: MINIO_ENDPOINT
    value: "minio"
  - name: MINIO_PORT
    value: "9000"
  - name: MINIO_USE_SSL
    value: "false"
  - name: MINIO_ACCESS_KEY
    value: "minioadmin"
  - name: MINIO_SECRET_KEY
    value: "minioadmin"
  - name: MINIO_BUCKET
    value: "ingest"
