// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: services/anchor-service/proto/anchor_submit.proto

package anchorsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// minimal request descriptor for gRPC signer/submitter
type AnchorSubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"` // hex with or without 0x
	PreviewIds    []string               `protobuf:"bytes,3,rep,name=preview_ids,json=previewIds,proto3" json:"preview_ids,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	EstimatedGas  uint64                 `protobuf:"varint,5,opt,name=estimated_gas,json=estimatedGas,proto3" json:"estimated_gas,omitempty"`
	Submitter     string                 `protobuf:"bytes,6,opt,name=submitter,proto3" json:"submitter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorSubmitRequest) Reset() {
	*x = AnchorSubmitRequest{}
	mi := &file_services_anchor_service_proto_anchor_submit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorSubmitRequest) ProtoMessage() {}

func (x *AnchorSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_anchor_service_proto_anchor_submit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorSubmitRequest.ProtoReflect.Descriptor instead.
func (*AnchorSubmitRequest) Descriptor() ([]byte, []int) {
	return file_services_anchor_service_proto_anchor_submit_proto_rawDescGZIP(), []int{0}
}

func (x *AnchorSubmitRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnchorSubmitRequest) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *AnchorSubmitRequest) GetPreviewIds() []string {
	if x != nil {
		return x.PreviewIds
	}
	return nil
}

func (x *AnchorSubmitRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *AnchorSubmitRequest) GetEstimatedGas() uint64 {
	if x != nil {
		return x.EstimatedGas
	}
	return 0
}

func (x *AnchorSubmitRequest) GetSubmitter() string {
	if x != nil {
		return x.Submitter
	}
	return ""
}

// response from signer-submitter
type AnchorSubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	MerkleRoot    string                 `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,4,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                              // "success"|"failed"
	SubmittedAt   string                 `protobuf:"bytes,6,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorSubmitResponse) Reset() {
	*x = AnchorSubmitResponse{}
	mi := &file_services_anchor_service_proto_anchor_submit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorSubmitResponse) ProtoMessage() {}

func (x *AnchorSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_anchor_service_proto_anchor_submit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorSubmitResponse.ProtoReflect.Descriptor instead.
func (*AnchorSubmitResponse) Descriptor() ([]byte, []int) {
	return file_services_anchor_service_proto_anchor_submit_proto_rawDescGZIP(), []int{1}
}

func (x *AnchorSubmitResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AnchorSubmitResponse) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *AnchorSubmitResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *AnchorSubmitResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *AnchorSubmitResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnchorSubmitResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

var File_services_anchor_service_proto_anchor_submit_proto protoreflect.FileDescriptor

const file_services_anchor_service_proto_anchor_submit_proto_rawDesc = "" +
	"\n" +
	"1services/anchor-service/proto/anchor_submit.proto\x12\tanchorsvc\"\xd1\x01\n" +
	"\x13AnchorSubmitRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\tR\n" +
	"merkleRoot\x12\x1f\n" +
	"\vpreview_ids\x18\x03 \x03(\tR\n" +
	"previewIds\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\x12#\n" +
	"\restimated_gas\x18\x05 \x01(\x04R\festimatedGas\x12\x1c\n" +
	"\tsubmitter\x18\x06 \x01(\tR\tsubmitter\"\xcd\x01\n" +
	"\x14AnchorSubmitResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\tR\n" +
	"merkleRoot\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12!\n" +
	"\fblock_number\x18\x04 \x01(\x04R\vblockNumber\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fsubmitted_at\x18\x06 \x01(\tR\vsubmittedAt2f\n" +
	"\x13AnchorSubmitService\x12O\n" +
	"\fSubmitAnchor\x12\x1e.anchorsvc.AnchorSubmitRequest\x1a\x1f.anchorsvc.AnchorSubmitResponseBIZGgithub.com/yourorg/majorproject/services/anchor-service/proto;anchorsvcb\x06proto3"

var (
	file_services_anchor_service_proto_anchor_submit_proto_rawDescOnce sync.Once
	file_services_anchor_service_proto_anchor_submit_proto_rawDescData []byte
)

func file_services_anchor_service_proto_anchor_submit_proto_rawDescGZIP() []byte {
	file_services_anchor_service_proto_anchor_submit_proto_rawDescOnce.Do(func() {
		file_services_anchor_service_proto_anchor_submit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_anchor_service_proto_anchor_submit_proto_rawDesc), len(file_services_anchor_service_proto_anchor_submit_proto_rawDesc)))
	})
	return file_services_anchor_service_proto_anchor_submit_proto_rawDescData
}

var file_services_anchor_service_proto_anchor_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_anchor_service_proto_anchor_submit_proto_goTypes = []any{
	(*AnchorSubmitRequest)(nil),  // 0: anchorsvc.AnchorSubmitRequest
	(*AnchorSubmitResponse)(nil), // 1: anchorsvc.AnchorSubmitResponse
}
var file_services_anchor_service_proto_anchor_submit_proto_depIdxs = []int32{
	0, // 0: anchorsvc.AnchorSubmitService.SubmitAnchor:input_type -> anchorsvc.AnchorSubmitRequest
	1, // 1: anchorsvc.AnchorSubmitService.SubmitAnchor:output_type -> anchorsvc.AnchorSubmitResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_anchor_service_proto_anchor_submit_proto_init() }
func file_services_anchor_service_proto_anchor_submit_proto_init() {
	if File_services_anchor_service_proto_anchor_submit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_anchor_service_proto_anchor_submit_proto_rawDesc), len(file_services_anchor_service_proto_anchor_submit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_anchor_service_proto_anchor_submit_proto_goTypes,
		DependencyIndexes: file_services_anchor_service_proto_anchor_submit_proto_depIdxs,
		MessageInfos:      file_services_anchor_service_proto_anchor_submit_proto_msgTypes,
	}.Build()
	File_services_anchor_service_proto_anchor_submit_proto = out.File
	file_services_anchor_service_proto_anchor_submit_proto_goTypes = nil
	file_services_anchor_service_proto_anchor_submit_proto_depIdxs = nil
}
